apiVersion: v1
kind: Service
metadata:
  name: kubeservice
spec:
  selector:
    app: kubeoperation
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeoperation
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kubeoperation
  template:
    metadata:
      labels:
        app: kubeoperation
    spec:
      containers:
        - name: kubecontainer
          image: justinamutigliengo/dockeroperation:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              value: mongodb+srv://coder_72830:coder2025@clustercoder.zi5pkou.mongodb.net/?retryWrites=true&w=majority&appName=ClusterCoder
          imagePullPolicy: Always
